import { Household } from "./types";

export const DEMO_HOUSEHOLD: Household = {
  state: "Madhya Pradesh",
  area: "rural",
  category: "obc",
  annualIncome: 200000,
  ownsFarmland: true,
  rationCard: "bpl",
  members: [
    {
      id: "mem-self",
      relation: "self",
      name: "Ramesh",
      age: 48,
      gender: "male",
      maritalStatus: "married",
      education: "class_10",
      occupation: "farmer",
    },
    {
      id: "mem-spouse",
      relation: "spouse",
      name: "Sunita",
      age: 44,
      gender: "female",
      maritalStatus: "married",
      education: "primary",
      occupation: "homemaker",
    },
    {
      id: "mem-son",
      relation: "son",
      name: "Aman",
      age: 17,
      gender: "male",
      maritalStatus: "single",
      education: "class_10",
      occupation: "student",
      currentCourse: "Class 12",
    },
    {
      id: "mem-daughter",
      relation: "daughter",
      name: "Pooja",
      age: 9,
      gender: "female",
      maritalStatus: "single",
      education: "primary",
      occupation: "student",
    },
    {
      id: "mem-mother",
      relation: "mother",
      name: "Kamla",
      age: 67,
      gender: "female",
      maritalStatus: "widowed",
      education: "none",
      occupation: "homemaker",
    },
  ],
};
